/**
 * Car Rental Webservice
 * This is backend web service for the Car Rental application. For further information, please visit our [Wiki](https://se-2022.atlassian.net/wiki/)
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface User { 
    id?: string;
    first_name?: string;
    last_name?: string;
    address?: string;
    postal_code?: number;
    country?: string;
    e_mail?: string;
    phone?: string;
    customer_group?: string;
    status?: string;
}

